# -*- coding: utf-8 -*-
"""25.1 GS Vinicius, Henrique, Kaio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-mHEYaios5sRj_xnJW2jtXXJZ3kKK4o
"""

quantidade_desastre = int(input("Digite a quantidade de desastres? "))
total_pessoas_afetadas_list = []
numero_criancas_list = []
numero_adultos_list = []
numero_idosos_list = []
numero_pessoas_mobilidade_reduzida_list = []
numero_feridos_list = []
dados_desastres = []
erro = False

for i in range(quantidade_desastre):
  tipo_desastre = input('Insira Tipo do Desastre: ' )
  pais= input('Digite o País: ')
  cidade=input('Digite a Cidade: ')
  bairro= input('Digite o Bairro: ')
  rua = input('Digite a Rua: ')
  

  total_pessoas_afetadas = int(input('Digite o total de pessoas afetadas: '))
  total_pessoas_afetadas_list.append(total_pessoas_afetadas)

  numero_criancas = int(input('Digite o numero de crianças: '))
  numero_criancas_list.append(numero_criancas)

  numero_adultos = int(input('Digite o numero de adultos: '))
  numero_adultos_list.append(numero_adultos)

  numero_idosos= int(input('Digite o numero de idosos: '))
  numero_idosos_list.append(numero_idosos)

  numero_pessoas_mobilidade_reduzida = int(input('Digite o numero de pessoas mobilidade reduzida: '))
  numero_pessoas_mobilidade_reduzida_list.append(numero_pessoas_mobilidade_reduzida)

  numero_feridos = int(input('Digite o numero de pessoas feridas: '))
  numero_feridos_list.append(numero_feridos)

  print('')

  if total_pessoas_afetadas == (numero_criancas + numero_adultos + numero_idosos + numero_pessoas_mobilidade_reduzida + numero_feridos):
    dados_desastres.append([tipo_desastre, pais, cidade, bairro, rua, total_pessoas_afetadas, 
                                numero_criancas, numero_adultos, numero_idosos, numero_pessoas_mobilidade_reduzida, numero_feridos])
  else:
    print('Erro, Tente Novamente')
    erro = True
    break
      
    lista_desastre = [tipo_desastre, pais, cidade, bairro, rua, total_pessoas_afetadas]
    lista_categoria = [numero_criancas_list, numero_adultos_list, numero_idosos_list, numero_pessoas_mobilidade_reduzida_list, numero_feridos_list]
 
if not erro:
  print(f'Total de Desastres registrados: {quantidade_desastre} ')
  print('')
 
  print(f'Resumo de pessoas afetadas por categoria:\nCrianças: {sum(numero_criancas_list)} | Adultos: {sum(numero_adultos_list)} | Idosos: {sum(numero_idosos_list)} | Mobilidade Reduzida: {sum(numero_pessoas_mobilidade_reduzida_list)} | Feridos: {sum(numero_feridos_list)}')
  print('')
 
  categorias = ['Crianças', 'Adultos', 'Idosos', 'Mobilidade Reduzida', 'Feridos']
  valores = [sum(numero_criancas_list), sum(numero_adultos_list), sum(numero_idosos_list), sum(numero_pessoas_mobilidade_reduzida_list), sum(numero_feridos_list)]
  indice_maior = valores.index(max(valores))
  categoria_mais_afetada = categorias[indice_maior]
 
  print(f'Categoria mais afetada: {categoria_mais_afetada}')
  print(f'Total de Pessoas afetadas: {sum(total_pessoas_afetadas_list)}')
  print('')
 
  desastre_mais_afetado = dados_desastres[0]
 
 
  for desastre in dados_desastres:
      if desastre[5] > desastre_mais_afetado[5]:
          desastre_mais_afetado = desastre
 
  print(f'Desastre com maior número de afetados: \nTipo: {desastre_mais_afetado[0]} \nLocal: {desastre_mais_afetado[4]}, {desastre_mais_afetado[3]}, {desastre_mais_afetado[2]}, {desastre_mais_afetado[1]}')
