# -*- coding: utf-8 -*-
"""25.1 GS Vinicius, Henrique, Kaio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-mHEYaios5sRj_xnJW2jtXXJZ3kKK4o
"""

quantidade_desastre = int(input("Digite a quantidade de desastres?"))

for i in range(quantidade_desastre):
  tipo_desastre = input('Insira Tipo do Desastre: ' )
  pais= input('Digite o País: ')
  cidade=input('Digite a Cidade: ')
  bairro= input('Digite o Bairro: ')
  rua = input('Digite a Rua: ')
  total_pessoas_afetadas = int(input('Digite o total de pessoas afetadas: '))
  numero_criancas = int(input('Digite o numero de crianças: '))
  numero_adultos = int(input('Digite o numero de adultos: '))
  numero_idosos= int(input('Digite o numero de idosos: '))
  numero_pessoas_mobilidade_reduzida = int(input('Digite o numero de pessoas mobilidade reduzida: '))
  numero_feridos = int(input('Digite o numero de pessoas feridas: '))
  if total_pessoas_afetadas == (numero_criancas + numero_adultos + numero_idosos + numero_pessoas_mobilidade_reduzida + numero_feridos):
    print('')
  else:
    print('Erro, Tente Novamente')
